### ISSUE TITLE
Indention issues in Assembly blocks

### ISSUE THREAD

**Issue by ChrisChinchilla** [protofire/solhint#120] opened 2019-05-27 11:57 UTC
As far as I can see from my testing, solhint doesn't notice indentation issues inside `assembly{}` blocks.

**Comment by fvictorio** [comment] 2019-05-27 16:55
Thanks @ChrisChinchilla! While this does seem like a bug, we are starting to delegate this kind of checks to the [Prettier plugin](https://github.com/prettier-solidity/prettier-plugin-solidity/), so you might want to try that along with the [`solhint-prettier-plugin`](https://github.com/fvictorio/solhint-plugin-prettier).

**Comment by ChrisChinchilla** [comment] 2019-05-29 08:29
@fvictorio So I understand correctly here. I typically thought prettier fixed formatting issues, whereas a linter identifies them, so isn't this the job of a linter?

**Comment by fvictorio** [comment] 2019-05-29 18:04
Yeah, the idea is for prettier to do the formatting, and for solhint to let you know when your code is not formatted as prettier would do it. Similar to how you use `eslint` and `eslint-plugin-prettier`. Does that make sense?

**Comment by ChrisChinchilla** [comment] 2019-05-30 12:10
Yes, but I don't think this addresses my initial question/report… So I think this is a bug in the linter, and is it one that should be fixed here or not?

Or are you saying that any formatting violations are just handled by prettier and passed back to the linter? If that's the case, will it report what the issue is? And not just "prettier says there's a problem"? Just trying to understand what this will look like :)

**Comment by fvictorio** [comment] 2019-05-30 12:53
Oh, yes, let me clarify.

The issue you are reporting is right. But fixing it will probably be very low priority for us, since working on that stuff sort of duplicates the work done on `prettier-plugin-solidity`. That's why we encourage people to use that.

With respect to the report: it will tell you where the problem is, and how to fix it, but in practice it's not a very readable message (not cryptic, just not *that* useful). You can see some examples in the [eslint plugin](https://github.com/prettier/eslint-plugin-prettier) readme, since we use the same underlying library.

So when that happens, you either run prettier on the file, or fix it manually if you immediately detect the problem ("oh, I entered two spaces"). That's my experience at least.

Hope that makes sense!

**Comment by ChrisChinchilla** [comment] 2019-06-11 11:14
Thanks @fvictorio we're actually linting the code blocks in the Solidity docs, so prettier isn't an option right now, but thanks for the heads up and I will use it in standalone contracts

**Comment by fvictorio** [comment] 2020-05-04 14:34
Closing this since we removed all styiling rules and probably won't fix this in 2.0.

**Closed by fvictorio** 2020-05-04 14:34 UTC
